# Dependencies

# Permalinks
permalink:        pretty

# Setup
title:            springyRecords
tagline:          'A frawework to generate Data Access Classes.'
description:      'Generate record and table data gateway classes that run on top of spring-jdbc.'
url:              http://huherto.github.io/springyRecords/
baseurl:          /springyRecords

author:
  name:           'Humberto Hernandez'
  url:            https://twitter.com/huherto

paginate:         5

# Custom vars
version:          master

github:
  repo:           https://github.com/huherto/springyRecords
theme: jekyll-theme-cayman
